# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\trainproj_soft\trainproj_soft\UI\train.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1690, 1250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_window = QtWidgets.QFrame(self.centralwidget)
        self.frame_window.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_window.setStyleSheet("QFrame{\n"
"    background-color:rgb(206, 206, 206);\n"
"}")
        self.frame_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_window.setObjectName("frame_window")
        self.pushButton = QtWidgets.QPushButton(self.frame_window)
        self.pushButton.setGeometry(QtCore.QRect(60, 1180, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 135, 163)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 760, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 610, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 460, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 300, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.frame_window)
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setStyleSheet("QFrame{\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.System_name = QtWidgets.QLabel(self.frame_menu)
        self.System_name.setGeometry(QtCore.QRect(270, 30, 721, 81))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.System_name.setFont(font)
        self.System_name.setTextFormat(QtCore.Qt.AutoText)
        self.System_name.setAlignment(QtCore.Qt.AlignCenter)
        self.System_name.setObjectName("System_name")
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setGeometry(QtCore.QRect(150, 710, 201, 441))
        self.label.setStyleSheet("border-image:url(:/machine/下煤机.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.frame_menu)
        self.frame.setGeometry(QtCore.QRect(560, 710, 861, 461))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:rgb(225, 225, 225)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_wh_2 = QtWidgets.QLabel(self.frame)
        self.label_wh_2.setGeometry(QtCore.QRect(70, 140, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_2.setFont(font)
        self.label_wh_2.setObjectName("label_wh_2")
        self.label_wh_3 = QtWidgets.QLabel(self.frame)
        self.label_wh_3.setGeometry(QtCore.QRect(70, 230, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_3.setFont(font)
        self.label_wh_3.setObjectName("label_wh_3")
        self.label_wh_4 = QtWidgets.QLabel(self.frame)
        self.label_wh_4.setGeometry(QtCore.QRect(70, 320, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_4.setFont(font)
        self.label_wh_4.setObjectName("label_wh_4")
        self.label_wh_6 = QtWidgets.QLabel(self.frame)
        self.label_wh_6.setGeometry(QtCore.QRect(480, 50, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_6.setFont(font)
        self.label_wh_6.setObjectName("label_wh_6")
        self.label_wh_7 = QtWidgets.QLabel(self.frame)
        self.label_wh_7.setGeometry(QtCore.QRect(480, 170, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_7.setFont(font)
        self.label_wh_7.setObjectName("label_wh_7")
        self.label_wh_5 = QtWidgets.QLabel(self.frame)
        self.label_wh_5.setGeometry(QtCore.QRect(480, 290, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_5.setFont(font)
        self.label_wh_5.setObjectName("label_wh_5")
        self.label_wh_8 = QtWidgets.QLabel(self.frame)
        self.label_wh_8.setGeometry(QtCore.QRect(60, 50, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh_8.setFont(font)
        self.label_wh_8.setObjectName("label_wh_8")
        self.textBrowser_chk_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_2.setGeometry(QtCore.QRect(220, 60, 160, 50))
        self.textBrowser_chk_2.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_2.setObjectName("textBrowser_chk_2")
        self.textBrowser_chk_3 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_3.setGeometry(QtCore.QRect(220, 160, 160, 50))
        self.textBrowser_chk_3.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_3.setObjectName("textBrowser_chk_3")
        self.textBrowser_chk_4 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_4.setGeometry(QtCore.QRect(220, 250, 160, 50))
        self.textBrowser_chk_4.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_4.setObjectName("textBrowser_chk_4")
        self.textBrowser_chk_5 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_5.setGeometry(QtCore.QRect(220, 340, 160, 50))
        self.textBrowser_chk_5.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_5.setObjectName("textBrowser_chk_5")
        self.textBrowser_chk_6 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_6.setGeometry(QtCore.QRect(610, 310, 160, 50))
        self.textBrowser_chk_6.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_6.setObjectName("textBrowser_chk_6")
        self.textBrowser_chk_7 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_7.setGeometry(QtCore.QRect(610, 190, 160, 50))
        self.textBrowser_chk_7.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_7.setObjectName("textBrowser_chk_7")
        self.textBrowser_chk_8 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_chk_8.setGeometry(QtCore.QRect(610, 70, 160, 50))
        self.textBrowser_chk_8.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk_8.setObjectName("textBrowser_chk_8")
        self.label_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_2.setGeometry(QtCore.QRect(20, 300, 511, 241))
        self.label_2.setStyleSheet("border-image:url(:/train/火车.jpg)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_menu)
        self.frame_2.setGeometry(QtCore.QRect(560, 170, 861, 461))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color:rgb(225, 225, 225)\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_qy = QtWidgets.QLabel(self.frame_2)
        self.label_qy.setGeometry(QtCore.QRect(60, 40, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy.setFont(font)
        self.label_qy.setObjectName("label_qy")
        self.label_wh = QtWidgets.QLabel(self.frame_2)
        self.label_wh.setGeometry(QtCore.QRect(60, 120, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wh.setFont(font)
        self.label_wh.setObjectName("label_wh")
        self.label_czy = QtWidgets.QLabel(self.frame_2)
        self.label_czy.setGeometry(QtCore.QRect(60, 210, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_czy.setFont(font)
        self.label_czy.setObjectName("label_czy")
        self.label_lch = QtWidgets.QLabel(self.frame_2)
        self.label_lch.setGeometry(QtCore.QRect(60, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_lch.setFont(font)
        self.label_lch.setObjectName("label_lch")
        self.textBrowser_xtzt = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_xtzt.setGeometry(QtCore.QRect(260, 50, 160, 50))
        self.textBrowser_xtzt.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_xtzt.setObjectName("textBrowser_xtzt")
        self.textBrowser_chk = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_chk.setGeometry(QtCore.QRect(260, 140, 160, 50))
        self.textBrowser_chk.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_chk.setObjectName("textBrowser_chk")
        self.textBrowser_czy = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_czy.setGeometry(QtCore.QRect(260, 230, 160, 50))
        self.textBrowser_czy.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_czy.setObjectName("textBrowser_czy")
        self.textBrowser_lch = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_lch.setGeometry(QtCore.QRect(260, 320, 160, 50))
        self.textBrowser_lch.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(217, 255, 187)\n"
"}")
        self.textBrowser_lch.setObjectName("textBrowser_lch")
        self.Train_graph = QtWidgets.QGraphicsView(self.frame_2)
        self.Train_graph.setGeometry(QtCore.QRect(490, 40, 341, 361))
        self.Train_graph.setStyleSheet("QGraphicsView{\n"
"background-color:rgb(225, 255, 253)\n"
"}\n"
"")
        self.Train_graph.setObjectName("Train_graph")
        self.label_train = QtWidgets.QLabel(self.frame_2)
        self.label_train.setGeometry(QtCore.QRect(610, 400, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_train.setFont(font)
        self.label_train.setObjectName("label_train")
        self.horizontalLayout.addWidget(self.frame_menu)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "退出"))
        self.pushButton_5.setText(_translate("MainWindow", "火车视觉识别"))
        self.pushButton_6.setText(_translate("MainWindow", "下料机控制"))
        self.pushButton_7.setText(_translate("MainWindow", "下料历史查询"))
        self.pushButton_8.setText(_translate("MainWindow", "火车型号尺寸"))
        self.System_name.setText(_translate("MainWindow", "火车加料智能监控系统"))
        self.label_wh_2.setText(_translate("MainWindow", "阀门开度"))
        self.label_wh_3.setText(_translate("MainWindow", "升降高度"))
        self.label_wh_4.setText(_translate("MainWindow", "翻板高度"))
        self.label_wh_6.setText(_translate("MainWindow", "是否装满"))
        self.label_wh_7.setText(_translate("MainWindow", "装料进度"))
        self.label_wh_5.setText(_translate("MainWindow", "料面高度"))
        self.label_wh_8.setText(_translate("MainWindow", "下煤机状态"))
        self.textBrowser_chk_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">正常</span></p></body></html>"))
        self.textBrowser_chk_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">30度</span></p></body></html>"))
        self.textBrowser_chk_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">20cm</span></p></body></html>"))
        self.textBrowser_chk_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">10cm</span></p></body></html>"))
        self.textBrowser_chk_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2.7米</span></p></body></html>"))
        self.textBrowser_chk_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">40%</span></p></body></html>"))
        self.textBrowser_chk_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">否</span></p></body></html>"))
        self.label_qy.setText(_translate("MainWindow", "牵引系统状态"))
        self.label_wh.setText(_translate("MainWindow", "仓库号"))
        self.label_czy.setText(_translate("MainWindow", "操作员"))
        self.label_lch.setText(_translate("MainWindow", "列车号"))
        self.textBrowser_xtzt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">正常</span></p></body></html>"))
        self.textBrowser_chk.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">WH0293</span></p></body></html>"))
        self.textBrowser_czy.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">张三</span></p></body></html>"))
        self.textBrowser_lch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00001</p></body></html>"))
        self.label_train.setText(_translate("MainWindow", "监控区域"))
import pictures_rc
