# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\trainproj_soft\trainproj_soft\UI\machine_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_layoff_history(object):
    def setupUi(self, layoff_history):
        layoff_history.setObjectName("layoff_history")
        layoff_history.resize(1690, 1250)
        self.centralwidget = QtWidgets.QWidget(layoff_history)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_window = QtWidgets.QFrame(self.centralwidget)
        self.frame_window.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_window.setStyleSheet("QFrame{\n"
"    background-color:rgb(206, 206, 206);\n"
"}")
        self.frame_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_window.setObjectName("frame_window")
        self.pushButton = QtWidgets.QPushButton(self.frame_window)
        self.pushButton.setGeometry(QtCore.QRect(60, 1180, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 135, 163)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 760, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 610, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 460, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 300, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.frame_window)
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setStyleSheet("QFrame{\n"
"    background-color:rgb(225, 255, 253)\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.System_name = QtWidgets.QLabel(self.frame_menu)
        self.System_name.setGeometry(QtCore.QRect(310, 40, 721, 81))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.System_name.setFont(font)
        self.System_name.setTextFormat(QtCore.Qt.AutoText)
        self.System_name.setAlignment(QtCore.Qt.AlignCenter)
        self.System_name.setObjectName("System_name")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_menu)
        self.textBrowser.setGeometry(QtCore.QRect(90, 630, 711, 421))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(255, 255, 255)\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.label_qy = QtWidgets.QLabel(self.frame_menu)
        self.label_qy.setGeometry(QtCore.QRect(920, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy.setFont(font)
        self.label_qy.setObjectName("label_qy")
        self.textEdit = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit.setGeometry(QtCore.QRect(1080, 320, 251, 41))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_9.setGeometry(QtCore.QRect(970, 510, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_qy_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_2.setGeometry(QtCore.QRect(920, 210, 391, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_2.setFont(font)
        self.label_qy_2.setObjectName("label_qy_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_11.setGeometry(QtCore.QRect(90, 1100, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.history_graph = QtWidgets.QGraphicsView(self.frame_menu)
        self.history_graph.setGeometry(QtCore.QRect(90, 200, 711, 381))
        self.history_graph.setStyleSheet("QGraphicsView{\n"
" background-color:rgb(255, 242, 208)\n"
"}")
        self.history_graph.setObjectName("history_graph")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_12.setGeometry(QtCore.QRect(270, 1100, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_13.setGeometry(QtCore.QRect(460, 1100, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_14.setGeometry(QtCore.QRect(650, 1100, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_qy_3 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_3.setGeometry(QtCore.QRect(920, 390, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_3.setFont(font)
        self.label_qy_3.setObjectName("label_qy_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_2.setGeometry(QtCore.QRect(1080, 410, 251, 41))
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_qy_4 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_4.setGeometry(QtCore.QRect(930, 680, 391, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_4.setFont(font)
        self.label_qy_4.setObjectName("label_qy_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_10.setGeometry(QtCore.QRect(960, 800, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_15.setGeometry(QtCore.QRect(960, 900, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.frame_menu)
        layoff_history.setCentralWidget(self.centralwidget)

        self.retranslateUi(layoff_history)
        QtCore.QMetaObject.connectSlotsByName(layoff_history)

    def retranslateUi(self, layoff_history):
        _translate = QtCore.QCoreApplication.translate
        layoff_history.setWindowTitle(_translate("layoff_history", "MainWindow"))
        self.pushButton.setText(_translate("layoff_history", "退出"))
        self.pushButton_5.setText(_translate("layoff_history", "火车视觉识别"))
        self.pushButton_6.setText(_translate("layoff_history", "下料机控制"))
        self.pushButton_7.setText(_translate("layoff_history", "下料历史查询"))
        self.pushButton_8.setText(_translate("layoff_history", "火车型号尺寸"))
        self.System_name.setText(_translate("layoff_history", "下料历史趋势主界面"))
        self.textBrowser.setHtml(_translate("layoff_history", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">******************** Machine Table 数据 ********************</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MaterialID WarehouseID Volume Reporter OpenStatus RunStatus</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC001        WH01 500.00       张三         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC002        WH02 500.00       李四         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC003        WH03 600.00       王五         关闭        待机</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC004        WH04 550.00       赵六         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC005        WH05 600.00       钱七         关闭        维护</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC006        WH01 500.00       张三         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC007        WH02 500.00       李四         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC008        WH03 600.00       王五         关闭        待机</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC009        WH04 550.00       赵六         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC010        WH05 600.00       钱七         关闭        维护</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC011        WH01 500.00       张三         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC012        WH02 500.00       李四         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC013        WH03 600.00       王五         关闭        待机</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC014        WH04 550.00       赵六         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC015        WH05 600.00       钱七         关闭        维护</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC016        WH01 500.00       张三         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC017        WH02 500.00       李四         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC018        WH03 600.00       王五         关闭        待机</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC019        WH04 550.00       赵六         开启        运行</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     MC020        WH05 600.00       钱七         关闭        维护</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*****************************************************</p></body></html>"))
        self.label_qy.setText(_translate("layoff_history", "下料机号："))
        self.pushButton_9.setText(_translate("layoff_history", "开始查询"))
        self.label_qy_2.setText(_translate("layoff_history", "请输入查询的信息："))
        self.pushButton_11.setText(_translate("layoff_history", "10分"))
        self.pushButton_12.setText(_translate("layoff_history", "1小时"))
        self.pushButton_13.setText(_translate("layoff_history", "4小时"))
        self.pushButton_14.setText(_translate("layoff_history", "1天"))
        self.label_qy_3.setText(_translate("layoff_history", "仓库号："))
        self.label_qy_4.setText(_translate("layoff_history", "其他功能："))
        self.pushButton_10.setText(_translate("layoff_history", "生成Excel报表"))
        self.pushButton_15.setText(_translate("layoff_history", "打印表单"))
