# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\trainproj_soft\trainproj_soft\UI\train_warehouse_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainQuery(object):
    def setupUi(self, TrainQuery):
        TrainQuery.setObjectName("TrainQuery")
        TrainQuery.resize(1690, 1250)
        self.centralwidget = QtWidgets.QWidget(TrainQuery)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_window = QtWidgets.QFrame(self.centralwidget)
        self.frame_window.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_window.setStyleSheet("QFrame{\n"
"    background-color:rgb(206, 206, 206);\n"
"}")
        self.frame_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_window.setObjectName("frame_window")
        self.pushButton = QtWidgets.QPushButton(self.frame_window)
        self.pushButton.setGeometry(QtCore.QRect(60, 1180, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 135, 163)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 760, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 610, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 460, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 300, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color:rgb(243, 255, 189)\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.frame_window)
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setStyleSheet("QFrame{\n"
"    background-color:rgb(225, 255, 253)\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.System_name = QtWidgets.QLabel(self.frame_menu)
        self.System_name.setGeometry(QtCore.QRect(310, 10, 721, 81))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.System_name.setFont(font)
        self.System_name.setTextFormat(QtCore.Qt.AutoText)
        self.System_name.setAlignment(QtCore.Qt.AlignCenter)
        self.System_name.setObjectName("System_name")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_menu)
        self.textBrowser.setGeometry(QtCore.QRect(30, 630, 1351, 481))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(255, 255, 255)\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.label_qy = QtWidgets.QLabel(self.frame_menu)
        self.label_qy.setGeometry(QtCore.QRect(230, 230, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy.setFont(font)
        self.label_qy.setObjectName("label_qy")
        self.label_ls = QtWidgets.QLabel(self.frame_menu)
        self.label_ls.setGeometry(QtCore.QRect(620, 1120, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ls.setFont(font)
        self.label_ls.setObjectName("label_ls")
        self.textEdit = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit.setGeometry(QtCore.QRect(400, 250, 131, 41))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_9.setGeometry(QtCore.QRect(440, 1170, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_10.setGeometry(QtCore.QRect(760, 1170, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color:rgb(213, 227, 255)\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_qy_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_2.setGeometry(QtCore.QRect(230, 150, 391, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_2.setFont(font)
        self.label_qy_2.setObjectName("label_qy_2")
        self.label_qy_5 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_5.setGeometry(QtCore.QRect(590, 230, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_5.setFont(font)
        self.label_qy_5.setObjectName("label_qy_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_3.setGeometry(QtCore.QRect(740, 250, 131, 41))
        self.textEdit_3.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_qy_6 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_6.setGeometry(QtCore.QRect(940, 230, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_6.setFont(font)
        self.label_qy_6.setObjectName("label_qy_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_4.setGeometry(QtCore.QRect(1090, 250, 131, 41))
        self.textEdit_4.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_qy_7 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_7.setGeometry(QtCore.QRect(940, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_7.setFont(font)
        self.label_qy_7.setObjectName("label_qy_7")
        self.label_qy_8 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_8.setGeometry(QtCore.QRect(590, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_8.setFont(font)
        self.label_qy_8.setObjectName("label_qy_8")
        self.textEdit_6 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_6.setGeometry(QtCore.QRect(740, 320, 131, 41))
        self.textEdit_6.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_7.setGeometry(QtCore.QRect(1090, 320, 131, 41))
        self.textEdit_7.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_qy_9 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_9.setGeometry(QtCore.QRect(230, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_9.setFont(font)
        self.label_qy_9.setObjectName("label_qy_9")
        self.label_qy_10 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_10.setGeometry(QtCore.QRect(230, 370, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_10.setFont(font)
        self.label_qy_10.setObjectName("label_qy_10")
        self.label_qy_11 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_11.setGeometry(QtCore.QRect(940, 370, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_11.setFont(font)
        self.label_qy_11.setObjectName("label_qy_11")
        self.label_qy_12 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_12.setGeometry(QtCore.QRect(590, 370, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_12.setFont(font)
        self.label_qy_12.setObjectName("label_qy_12")
        self.textEdit_9 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_9.setGeometry(QtCore.QRect(1090, 390, 131, 41))
        self.textEdit_9.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_10.setGeometry(QtCore.QRect(400, 390, 131, 41))
        self.textEdit_10.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_8 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_8.setGeometry(QtCore.QRect(740, 390, 131, 41))
        self.textEdit_8.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_11 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_11.setGeometry(QtCore.QRect(400, 320, 131, 41))
        self.textEdit_11.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_qy_23 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_23.setGeometry(QtCore.QRect(940, 440, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_23.setFont(font)
        self.label_qy_23.setObjectName("label_qy_23")
        self.textEdit_21 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_21.setGeometry(QtCore.QRect(1090, 460, 131, 41))
        self.textEdit_21.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_21.setObjectName("textEdit_21")
        self.label_qy_24 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_24.setGeometry(QtCore.QRect(590, 440, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_24.setFont(font)
        self.label_qy_24.setObjectName("label_qy_24")
        self.label_qy_25 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_25.setGeometry(QtCore.QRect(230, 440, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_25.setFont(font)
        self.label_qy_25.setObjectName("label_qy_25")
        self.textEdit_20 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_20.setGeometry(QtCore.QRect(400, 460, 131, 41))
        self.textEdit_20.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_20.setObjectName("textEdit_20")
        self.textEdit_22 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_22.setGeometry(QtCore.QRect(740, 460, 131, 41))
        self.textEdit_22.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_22.setObjectName("textEdit_22")
        self.label_qy_26 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_26.setGeometry(QtCore.QRect(230, 510, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_26.setFont(font)
        self.label_qy_26.setObjectName("label_qy_26")
        self.label_qy_27 = QtWidgets.QLabel(self.frame_menu)
        self.label_qy_27.setGeometry(QtCore.QRect(590, 510, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_qy_27.setFont(font)
        self.label_qy_27.setObjectName("label_qy_27")
        self.textEdit_23 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_23.setGeometry(QtCore.QRect(400, 530, 131, 41))
        self.textEdit_23.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_23.setObjectName("textEdit_23")
        self.textEdit_24 = QtWidgets.QTextEdit(self.frame_menu)
        self.textEdit_24.setGeometry(QtCore.QRect(740, 530, 131, 41))
        self.textEdit_24.setStyleSheet("QTextEdit{\n"
"    background-color:rgb(255, 240, 226)\n"
"}")
        self.textEdit_24.setObjectName("textEdit_24")
        self.horizontalLayout.addWidget(self.frame_menu)
        TrainQuery.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainQuery)
        QtCore.QMetaObject.connectSlotsByName(TrainQuery)

    def retranslateUi(self, TrainQuery):
        _translate = QtCore.QCoreApplication.translate
        TrainQuery.setWindowTitle(_translate("TrainQuery", "MainWindow"))
        self.pushButton.setText(_translate("TrainQuery", "退出"))
        self.pushButton_5.setText(_translate("TrainQuery", "火车视觉识别"))
        self.pushButton_6.setText(_translate("TrainQuery", "下料机控制"))
        self.pushButton_7.setText(_translate("TrainQuery", "下料历史查询"))
        self.pushButton_8.setText(_translate("TrainQuery", "火车型号尺寸"))
        self.System_name.setText(_translate("TrainQuery", "火车型号尺寸 信息管理系统"))
        self.textBrowser.setHtml(_translate("TrainQuery", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">******************** Train Model Table 数据 ********************</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> TrainTypeID  HoldType  ExLength  ExWidth  ExHeight  InLength  InWidth  InHeight  Volume  Density  LoadWeight  FullLength  BottomHeight HookType</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        1001      Coal      20.5      3.2       4.5      18.5      2.8       4.0   200.0      0.8       150.0        25.0           1.2   Type-A       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        1002      Coal      22.0      3.5       4.8      20.0      3.0       4.3   250.0      0.8       180.0        27.0           1.3   Type-B       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        1003      Coal      18.0      3.0       4.0      16.0      2.5       3.5   160.0      0.8       120.0        23.0           1.1   Type-A       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        2001     Mixed      25.0      3.8       5.0      23.0      3.5       4.5   300.0      0.7       200.0        30.0           1.5   Type-C       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        2002     Mixed      24.0      3.6       4.8      22.0      3.3       4.3   280.0      0.7       190.0        29.0           1.4   Type-C       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        3001 Container      15.0      2.8       3.5      14.0      2.5       3.2   120.0      NaN         NaN        20.0           1.0   Type-D       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        3002      Bulk      19.0      3.1       4.2      17.0      2.8       3.8   180.0      0.9       140.0        24.0           1.2   Type-A       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        3003    Tanker      16.0      2.9       3.8      15.0      2.6       3.5   140.0      NaN         NaN        21.0           1.1   Type-E       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        4001      Coal      21.0      3.3       4.6      19.0      2.9       4.1   220.0      0.8       160.0        26.0           1.3   Type-B       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        4002     Mixed      23.0      3.7       4.9      21.0      3.4       4.4   290.0      0.7       195.0        28.0           1.4   Type-C       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        4003      Coal      17.0      2.9       3.9      15.5      2.6       3.6   150.0      0.8       110.0        22.0           1.0   Type-A       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        4004      Bulk      20.0      3.2       4.4      18.0      2.9       4.0   210.0      0.9       155.0        25.5           1.3   Type-B       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        5001 Container      14.0      2.7       3.3      13.0      2.4       3.0   110.0      NaN         NaN        19.0           0.9   Type-D       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        5002    Tanker      17.0      3.0       4.0      16.0      2.7       3.6   160.0      NaN         NaN        22.0           1.1   Type-E       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        5003      Coal      19.5      3.1       4.3      17.5      2.8       3.9   190.0      0.8       140.0        24.5           1.2   Type-A       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        6001     Mixed      26.0      3.9       5.2      24.0      3.6       4.7   320.0      0.7       210.0        31.0           1.6   Type-C       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        6002      Bulk      18.0      3.0       4.1      16.5      2.7       3.7   170.0      0.9       130.0        23.0           1.1   Type-B       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        6003      Coal      20.8      3.4       4.7      19.0      3.1       4.2   230.0      0.8       170.0        26.5           1.4   Type-B       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        7001 Container      16.5      3.0       3.7      15.5      2.7       3.4   150.0      NaN         NaN        21.5           1.1   Type-D       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        7002    Tanker      18.0      3.2       4.2      17.0      2.9       3.8   190.0      NaN         NaN        23.0           1.2   Type-E       </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*********************************************************</p></body></html>"))
        self.label_qy.setText(_translate("TrainQuery", "火车型号ID"))
        self.label_ls.setText(_translate("TrainQuery", "数据库结果"))
        self.pushButton_9.setText(_translate("TrainQuery", "新增"))
        self.pushButton_10.setText(_translate("TrainQuery", "修改"))
        self.label_qy_2.setText(_translate("TrainQuery", "请输入新增/修改的信息："))
        self.label_qy_5.setText(_translate("TrainQuery", "装料类型"))
        self.label_qy_6.setText(_translate("TrainQuery", "外部长度"))
        self.label_qy_7.setText(_translate("TrainQuery", "内部长度"))
        self.label_qy_8.setText(_translate("TrainQuery", "外部高度"))
        self.label_qy_9.setText(_translate("TrainQuery", "外部宽度"))
        self.label_qy_10.setText(_translate("TrainQuery", "内部宽度"))
        self.label_qy_11.setText(_translate("TrainQuery", "容量"))
        self.label_qy_12.setText(_translate("TrainQuery", "内部高度"))
        self.label_qy_23.setText(_translate("TrainQuery", "全长"))
        self.label_qy_24.setText(_translate("TrainQuery", "装车重量"))
        self.label_qy_25.setText(_translate("TrainQuery", "炭散密度"))
        self.label_qy_26.setText(_translate("TrainQuery", "底板面高"))
        self.label_qy_27.setText(_translate("TrainQuery", "车钩型号"))
